//! Inter-Process Communication (IPC) module
//!
//! This module handles communication between the Rust sync engine and the
//! .NET MAUI UI layer using gRPC over named pipes or Unix sockets.

pub mod grpc_server;
// The protocol module is generated by tonic-build from protocol.proto
// We'll include it directly in grpc_server.rs

use tonic::transport::Server;
use tracing::{info, error};

pub use grpc_server::{SyncEngineServer, start_grpc_server};

/// IPC configuration
#[derive(Debug, Clone)]
pub struct IpcConfig {
    /// Server address
    pub addr: String,
    /// Maximum message size in bytes
    pub max_message_size: usize,
    /// Enable TLS
    pub tls_enabled: bool,
}

impl Default for IpcConfig {
    fn default() -> Self {
        Self {
            addr: "127.0.0.1:50051".to_string(),
            max_message_size: 64 * 1024 * 1024, // 64MB
            tls_enabled: false,
        }
    }
}

/// IPC error types
#[derive(Debug, thiserror::Error)]
pub enum IpcError {
    #[error("Connection error: {0}")]
    Connection(String),

    #[error("Serialization error: {0}")]
    Serialization(String),

    #[error("Protocol error: {0}")]
    Protocol(String),

    #[error("Timeout error")]
    Timeout,
}

/// Result type for IPC operations
pub type IpcResult<T> = std::result::Result<T, IpcError>;
